server:
  port: 9000

# spring.elasticsearch.rest
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  elasticsearch:
    rest:
      uris:
        - http://192.168.200.100:9200


#dsl:
#  aaa: findhaHAdadada
#  ALL --- TRACE --- DEBUG --- INFO --WARN -- ERROR --OFF
logging:
  level:
    tracer: trace  #打开追踪器
    org.elasticsearch: trace
